## SPDX-License-Identifier: GPL-2.0-or-later
## Copyright 2026 Deadband Inc.

default stm32mp135d-myd-yf135
menu title MYD-YF135 Boot Menu
timeout 1

label stm32mp135d-myd-yf135
  kernel /boot/uImage
  devicetree /boot/stm32mp135d-myd-yf135.dtb
  append root=ubi0:boot rootfstype=ubifs ubi.mtd=UBI rw
