# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright 2026 Deadband Inc.
# RAUC system configuration for MYD-YF135
# A/B OTA with readonly factory fallback + overlay

[system]
compatible=myd-yf135
bootloader=uboot
machine-id=myd-yf135
data-directory=/var/lib/rauc

[slot.rootfs.a]
device=/dev/ubiblock0_0
type=ubifs
bootname=rootfs_a

[slot.rootfs.b]
device=/dev/ubiblock0_1
type=ubifs
bootname=rootfs_b

[slot.rootfs.factory]
device=/dev/ubiblock0_2
type=ubifs
bootname=rootfs_factory
readonly=true
