# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright 2026 Deadband Inc.
# RAUC system configuration for MYD-YF135
# A/B OTA with readonly factory fallback + overlay

[system]
compatible=myd-yf135
bootloader=uboot
data-directory=/var/lib/rauc
mountprefix=/run/rauc

[keyring]
# TODO: published keys are not currently included pending secure boot integration
# Verify cert validity against bundle signing time (as RTC is not guaranteed)
path=/etc/rauc/keyring.pem
use-bundle-signing-time=true

[slot.rootfs.a]
device=/dev/ubi0_0
type=ubifs
bootname=A

[slot.rootfs.b]
device=/dev/ubi0_1
type=ubifs
bootname=B

[slot.rootfs.factory]
device=/dev/ubi0_2
type=ubifs
bootname=factory
readonly=true
