# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright 2026 Deadband Inc.
---
name: Build

"on":
  push:
    branches:
      - main
      - "release/*"

  pull_request:
    branches:
      - main
      - "release/*"

  workflow_dispatch:

"jobs":
  lockfile:
    name: Check lockfile is up-to-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Set up Nix environment
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check lockfile
        uses: ./.github/actions/lockfile

  image:
    name: Build release image (nix)
    needs: lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up Nix environment
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          build-mode: nix-build
          nix-flake: .
          project-name: dbl-buildroot
          build-sdk: true

      - name: Upload image artifacts
        if: ${{ steps.build.outputs.images-dir != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: myd-yf135-images
          path: ${{ steps.build.outputs.images-dir }}/
          if-no-files-found: error

      - name: Upload SDK artifacts
        if: ${{ steps.build.outputs.sdk-dir != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: myd-yf135-sdk
          path: ${{ steps.build.outputs.sdk-dir }}/
          if-no-files-found: error

  debug:
    name: Build debug image (make)
    needs: lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up Nix environment
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          build-mode: shell
          nix-flake: .
          build-command: make SHARE_HOST_FOR_DEBUG=0 debug  # No release build; do not share host toolchain
          project-name: dbl-buildroot
          images-path: output/debug/images/
          dl-cache-path: dl/
          ccache-path: output/ccache/
          host-cache-paths: |
            output/debug/host/
            output/debug/build/host-*/
          dl-key-files: buildroot.lock
          ccache-key-files: >-
            configs/myd_yf135_defconfig
            configs/myd_yf135_debug.fragment
            board/myd-yf135/linux.config
            board/myd-yf135/linux-debug.fragment
            board/myd-yf135/uboot.config
            board/myd-yf135/uboot-debug.fragment
          host-key-files: >-
            buildroot.lock
            configs/myd_yf135_defconfig
            configs/myd_yf135_debug.fragment

      - name: Upload debug image artifacts
        if: ${{ steps.build.outputs.images-dir != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: myd-yf135-debug-images
          path: ${{ steps.build.outputs.images-dir }}/
          if-no-files-found: error
